[build]
  command = "yarn build"
  publish = "build"

[functions]
  directory = "src/lambda"  # Spécifiez le bon répertoire pour vos fonctions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
